// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3Smnlbk3lTDc2rCdhaJ9BnLWhQLL_AA',
    appId: '1:638864758653:web:c633760d3a61e867abde14',
    messagingSenderId: '638864758653',
    projectId: 'chatappflutter-7300f',
    authDomain: 'chatappflutter-7300f.firebaseapp.com',
    storageBucket: 'chatappflutter-7300f.appspot.com',
    measurementId: 'G-SB4V8NFB5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKc4dV3tNZRvJQhpr6KbBXdEHuMcPjBv4',
    appId: '1:638864758653:android:6e83d9aa6c671085abde14',
    messagingSenderId: '638864758653',
    projectId: 'chatappflutter-7300f',
    storageBucket: 'chatappflutter-7300f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABmnoJjqAGzgZbBf64D4nykFbkJwj7KGg',
    appId: '1:638864758653:ios:6835f6c714160e6dabde14',
    messagingSenderId: '638864758653',
    projectId: 'chatappflutter-7300f',
    storageBucket: 'chatappflutter-7300f.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABmnoJjqAGzgZbBf64D4nykFbkJwj7KGg',
    appId: '1:638864758653:ios:0439a81eff3e57e6abde14',
    messagingSenderId: '638864758653',
    projectId: 'chatappflutter-7300f',
    storageBucket: 'chatappflutter-7300f.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
